### ISSUE TITLE
struct.error :unpack requires a string argument of length 2

### ISSUE THREAD

**Issue by MayurNagar** [zafartahirov/fingerpi#16] opened 2017-11-24 09:52 UTC
I know this issue is already been addressed but still i am unable get through this. please help
specification : raspberry pi 2, 
                       finger print scanner-gt511c3
![image](https://user-images.githubusercontent.com/29056016/33204987-4cf46582-d12b-11e7-8ea8-87e88127ccad.png)

**Comment by zafartahirov** [comment] 2017-12-27 22:37
Added exception check for checksum. Thanks for catching -- closing as resolved.

In you case, the problem is that your sensor is not connected properly to the R-Pi. It could be different port number, different baudrate, or just wiring not right. As there is no way for me to debug it, and `demo.py` is not a diagnostic tool, closing this. Try using `interactive.py` if you are debugging your setup.

**Closed by zafartahirov** 2017-12-27 22:37 UTC

**Comment by VenethKumar0808** [comment] 2018-01-09 11:20
I get below error while giving your connection

Traceback (most recent call last):
  File "/home/pi/Veneth Project/fingerpi-master/demo.py", line 31, in <module>
    f.Open(extra_info = True, check_baudrate = True)
  File "/home/pi/Veneth Project/fingerpi-master/fingerpi/fingerpi.py", line 77, in Open
    response = self.getResponse()
  File "/home/pi/Veneth Project/fingerpi-master/fingerpi/fingerpi.py", line 50, in getResponse
    return decode_command_packet(bytearray(response))
  File "/home/pi/Veneth Project/fingerpi-master/fingerpi/base.py", line 103, in decode_command_packet
    raise Exception(str(e) + ' ' + str(packet[0]))
Exception: unpack requires a string argument of length 10 0

In base.py the line of 103 is

try:
        packet = struct.unpack(comm_struct(), packet)
    except Exception as e:
        raise Exception(str(e) + ' ' + str(packet[0]))    /* Line : 103 */

Please guide me how to fix it!

**Comment by zafartahirov** [comment] 2018-01-10 05:29
The error says: "I am expecting a packet of length 10, but got a packet of length 0. This means you are not receiving anything from the sensor. Which means that the port for the sensor is not configured correctly. Because `demo.py` was designed to work on some machines, but not all of them. Did you read the notice what you run `demo.py`? You are not supposed to use it -- use `interactive.py`

**Comment by VenethKumar0808** [comment] 2018-01-10 06:46
While running interactive.py on hitting open the command prompt is stuck

**Comment by zafartahirov** [comment] 2018-01-11 00:18
I added an option to choose your own serial port in the `interactive.py` -- If you cannot open the port that your sensor is connected to, it is your setup that is broken!

**Comment by Veneth** [comment] 2018-01-18 10:50
I can't understand, What did you say? Please explain me clearly!
