### ISSUE TITLE
RaspberryPi 3 compatability

### ISSUE THREAD

**Issue by Korll** [zafartahirov/fingerpi#2] opened 2017-01-11 11:55 UTC
As the Raspberry Pi Zero is still very scarse, I have attempted to apply your code and the GT511C3 to my RaspberryPi 3.

I first disabled the serial by adding 'enable_uart=1' and 'dtoverlay=pi3-miniuart-bt' (disable the bluetooth on the UART) at the end of /boot/config.txt

I also discovered that the default device node on the Pi 3 is different so instead of '/dev/ttyAMA0' it is '/dev/ttyS0'. 

> pi@raspberrypi:~ $ ls -l /dev/ttyS0
> crw-rw---- 1 root dialout 4, 64 Jan 11 11:45 /dev/ttyS0

I then went to change your code, in particular, file fingerpi/fingerpi/fingerpi.py at line 10 to reflect it. 

Surely enough this time around I came further then just: "Opening connection...". And looked like this:
```
Opening connection...
Changing baudrate...
Place the finger on the scanner and press <Enter>

Unknown Error occured None
Place the finger on the scanner and press <Enter>
```
Now, it doesn't do much. It doesn't turn on the LED nor does it recognize my finger being placed onto the device. I have previously tested the device with an Arduino (as there is much more code available apparently there) and it works fine.

What am I doing wrong? Is it not compatible at all?

**Comment by zafartahirov** [comment] 2017-01-11 19:38
I am pretty sure it is compatible, because it is a simple UART protocol. The first thing, have you tried using `/dev/serial0` instead of the `ttyS0`?

If you did, you should also try to run the connection without the `demo.py`:

```python
import fingerpi as fp
f = fp.FingerPi()
f.Open(extra_info = True, check_baudrate = True)
response = f.CmosLed(True)
print (response)
```

The `Unknown Error` is raised for anything that is not `NACK_FINGER_IS_NOT_PRESSED` error. So technically it could be any error, including wrong baudrate or `NACK_COMMAND_ERROR` (acknowledgement problem)

Run the above, post the results here, I will try to replicate

**Comment by zafartahirov** [comment] 2017-01-11 19:41
The `check_baudrate` tries to identify the baudrate in case you have changed it before. So, if you don't want to auto-detect it, just specify the baudrate

```python
f = fp.FingerPi(
  port = '/dev/ttyAMA0',
  baudrate = 9600,
  device_id = 0x01,
  timeout = 2)
```

**Comment by zafartahirov** [comment] 2017-01-11 20:24
As @Korll mentioned before, Pi 3 has a different serial connections as compared to Pi 2 and Pi Zero. `ttyS0` is reserver for bluetooth (I think).

Pi 3 UART is on pins 15 and 16, and you will need to use `/dev/ttyS0` to connect to it (sometimes you can use `/dev/serial0`). More infor [here](http://pi4j.com/pins/model-3b-rev1.html)

**Comment by fxrhxn** [comment] 2017-01-12 00:54
I followed the instructions from the link you provided. https://openenergymonitor.org/emon/node/12311. Basically I disabled the bluetooth with 'dtoverlay=pi3-disable-bt' in the config.txt so I can use the normal port '/dev/ttyAMA0'. When I did that I still couldn't get the fingerprint scanner up and working. :( Do you know what could be the issue? It still says 'Opening Connection ...' until I give up and take a nap.

**Comment by fxrhxn** [comment] 2017-01-12 04:23
Ok, quick update so far.. I managed to get some results. Here is what happens when I run the sample code provided
```
##############################
##Trial 1- UART Port '/dev/ttyAMA0'           
##############################
### Results = [{'ACK': False, 'Header': None, 'Parameter': None, 'DeviceID': None, 'Checksum': None}, None]

 import fingerpi as fp

f = fp.FingerPi(
  port = '/dev/ttyAMA0',
  baudrate = 9600,
  device_id = 0x01,
  timeout = 2)

f.Open(extra_info = True, check_baudrate = True)
response = f.CmosLed(True)
print (response)
```

```
##############################
##Trial 2- UART Port '/dev/serial0'           
##############################
### Results = [{'ACK': False, 'Header': None, 'Parameter': None, 'DeviceID': None, 'Checksum': None}, None]

 import fingerpi as fp

f = fp.FingerPi(
  port = '/dev/serial0',
  baudrate = 9600,
  device_id = 0x01,
  timeout = 2)

f.Open(extra_info = True, check_baudrate = True)
response = f.CmosLed(True)
print (response)
```

**Comment by zafartahirov** [comment] 2017-01-12 09:06
I don't think it was a good idea remapping the UART pins -- it is rather advance thing to do. 
SO, if `Open` returns empty results like you have shown before, it usually means that your UART wasn't open in the first place, or nothing was received back from UART.

Post the results of the following:
```
import time
import fingerpi as fp
f = fp.FingerPi(
  port = '/dev/serial0',
  baudrate = 9600,
  device_id = 0x01,
  timeout = 10)
t = time.time()
response = f.Open(extra_info = False, check_baudrate = False)
print 'Time to Tx/Rx:', time.time() - t
print 'Response:', response
```

That will give us an idea if the connection is established or not. Don't enable the `extra_info` -- it is only needed if you want to find out what is the serial number and manufacturer of the sensor. Also, don't enable `check_baudrate` -- it usually messes up with the baudrate settings in the sensor.

**Comment by fxrhxn** [comment] 2017-01-12 16:55
Here is the response for the code .

## 1st Try 

Time to Tx/Rx: 2.01872897148
Response: [{'ACK': False, 'Header': None, 'Parameter': None, 'DeviceID': None, 'Checksum': None}, 
None]

## 2nd Try

Time to Tx/Rx: 2.01679396629
Response: [{'ACK': False, 'Header': None, 'Parameter': None, 'DeviceID': None, 'Checksum': None}, None]

## 3rd Try

Time to Tx/Rx: 2.01851797104
Response: [{'ACK': False, 'Header': None, 'Parameter': None, 'DeviceID': None, 'Checksum': None}, None]

**Comment by fxrhxn** [comment] 2017-01-12 18:25
#### Could it be from my wiring setup? Here is a picture of how I wired the fingerprint scanner to the Raspberry Pi. The orange wire connects to TX(p14) on the Pi, and the green wire connects to RX(p15)
![photo 1](https://cloud.githubusercontent.com/assets/18017683/21902570/633f5b08-d8ca-11e6-8f28-c6e18fefb39d.JPG)

**Comment by zafartahirov** [comment] 2017-01-12 19:04
OK, this is a mess. I have no idea about the wiring -- it is just a picture of a resistor, and a whole bunch of wires in the background.

What is the voltage on the IOs? I think RPi3 uses 5V pins, which means you need a voltage divider. If you were using 5V for pinouts there is slim chance you destroyed the sensor -- the documentation says that it is rated for 3.3-6V, but I would still be careful.

Also, are you sure the pin choice is correct? [MSFT](https://developer.microsoft.com/en-us/windows/iot/docs/pinmappingsrpi) says it is 8 and 10, [Pi4J](http://pi4j.com/pins/model-3b-rev1.html) says it is 15 and 16, and you are using 14 and 15.

The wiring and connection is outside of the scope of this project -- my suggestion is to connect the output of your UART to an oscilloscope or signal analyzer to see if RPi3 pinout you are using is correct. Worst case, connect a voltmeter, and try to eyeball if the voltage changes during Tx phase. The fact that your `Open()` response is empty means that RPi is not connected to the sensor. Also, the time for packet roundtrip is 2 seconds, which is inconsistent with the setup -- we set it to 10. This could happen if your Rx is not connected properly.

**Comment by fxrhxn** [comment] 2017-01-23 22:18
Sorry for the late response. I was working on other aspects of my project(gui / web app). Anyways, I ordered a Raspberry Pi 2,  and connected the Pins like in the display, and this is the response that I receive. 
```

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    f.Open(extra_info = False, check_baudrate = False)
  File "/home/pi/Desktop/fingerpi/fingerpi/fingerpi.py", line 87, in Open
    response = self.getResponse()
  File "/home/pi/Desktop/fingerpi/fingerpi/fingerpi.py", line 50, in getResponse
    return decode_command_packet(bytearray(response))
  File "/home/pi/Desktop/fingerpi/fingerpi/base.py", line 102, in decode_command_packet
    raise Exception(str(e) + ' ' + str(packet[0]))
Exception: unpack requires a string argument of length 10 1


```
If I don't connect the transmission wire( black wire) to the recieving pin(RX) of the Pi, the LED lights up, but there is no response obviously. So that must mean I am able to send requests to the fingerprint scanner, but not receive responses like the one shown above. By the way here is the code that I am using(same one as before. )

```

import fingerpi as fp

'''
f = fp.FingerPi(
  port = '/dev/ttyAMA0',
  baudrate = 9600,
  device_id = 0x01)
'''

f = fp.FingerPi(port = '/dev/ttyAMA0', device_id = 0x01, baudrate = 9600)
f.Open(extra_info = False, check_baudrate = False)

response = f.CmosLed(True)

print (response)
```

**Comment by zafartahirov** [comment] 2017-01-23 22:32
Can you send this sequence of commands, and tell me what it returns?

```python
f = fp.FingerPi(port = '/dev/ttyAMA0', device_id = 0x01, baudrate = 9600)
print "Send status:", f.sendCommand('Open', extra_info=False)
response = f.serial.read(12)
print "Resp len:", len(response)
print "Resp:", response
print "Resp decode:", fp.decode_command_packet(bytearray(response))
```

**Comment by zafartahirov** [comment] 2017-01-23 22:37
The problem is that `fp.decode_command_packet` expects a `bytearray` in format `<BBHIH`, which is of length 10. It throws an error if the packet is of different format. If this is the case, you might have to process the responses manually.

**Comment by fxrhxn** [comment] 2017-01-23 22:39
Here is the response for the first code.

```
Send status:
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    print "Send status:", f.sendCommand('Open', extra_info=False)
TypeError: sendCommand() got an unexpected keyword argument 'extra_info'

```

**Comment by zafartahirov** [comment] 2017-01-23 22:42
Oh my bad!!!

```python
f = fp.FingerPi(port = '/dev/ttyAMA0', device_id = 0x01, baudrate = 9600)
print "Send status:", f.sendCommand('Open', extra_info=0x00)
response = f.serial.read(12)
print "Resp len:", len(response)
print "Resp:", response
print "Resp decode:", fp.decode_command_packet(bytearray(response))
```

**Comment by zafartahirov** [comment] 2017-01-23 22:43
OOOOps, my bad again!


```python
f = fp.FingerPi(port = '/dev/ttyAMA0', device_id = 0x01, baudrate = 9600)
print "Send status:", f.sendCommand('Open', parameter=0x00)
response = f.serial.read(12)
print "Resp len:", len(response)
print "Resp:", response
print "Resp decode:", fp.decode_command_packet(bytearray(response))
```

**Comment by fxrhxn** [comment] 2017-01-23 22:45
Lol, here is the response.
```

Send status: True
Resp len: 8
Resp: 0
Resp decode:
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    print "Resp decode:", fp.decode_command_packet(bytearray(response))
AttributeError: 'module' object has no attribute 'decode_command_packet'

```

**Comment by zafartahirov** [comment] 2017-01-23 22:51
OK, I think I know what the problem is -- the checksum is not being received correctly. If you look at the [command packet structure](https://github.com/zafartahirov/fingerpi/blob/master/fingerpi/structure.py), the first 8 bytes are the payload, and the last 2 are the checksums. This is still speculation -- can u run one last thing:

```python
f = fp.FingerPi(port = '/dev/ttyAMA0', device_id = 0x01, baudrate = 9600)
print "Send status:", f.sendCommand('Open', parameter=0x00)
response = f.serial.read(12)
print "Resp len:", len(response)
print "Resp:", bytearray(response)
```

**Comment by fxrhxn** [comment] 2017-01-23 22:53
Response : 

```
Send status: True
Resp len: 8
Resp: 00

```

**Comment by zafartahirov** [comment] 2017-01-23 22:57
goddamit -- this bytearray doesn't wanna show!

```python
f = fp.FingerPi(port = '/dev/ttyAMA0', device_id = 0x01, baudrate = 9600)
print "Send status:", f.sendCommand('Open', parameter=0x00)
response = f.serial.read(12)
print "Resp len:", len(response)
print "Response:", [hex(x) for x in response]
```

**Comment by fxrhxn** [comment] 2017-01-23 23:00
Response:
```
Send status: True
Resp len: 8
Response:
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    print "Response:", [hex(x) for x in response]
TypeError: hex() argument can't be converted to hex

```

**Comment by zafartahirov** [comment] 2017-01-23 23:02
Rerun the latest code

**Comment by fxrhxn** [comment] 2017-01-23 23:05
Do you mean this one?

```
f = fp.FingerPi(port = '/dev/ttyAMA0', device_id = 0x01, baudrate = 9600)
print "Send status:", f.sendCommand('Open', parameter=0x00)
response = f.serial.read(12)
print "Resp len:", len(response)
print "Response:", [hex(x) for x in response]

```

If so then the response is(still the same):
```

Send status: True
Resp len: 10
Response:
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    print "Response:", [hex(x) for x in response]
TypeError: hex() argument can't be converted to hex

```

**Comment by zafartahirov** [comment] 2017-01-23 23:11
No! I mean the latest one, which is 

```python
f = fp.FingerPi(port = '/dev/ttyAMA0', device_id = 0x01, baudrate = 9600)
print "Send status:", f.sendCommand('Open', parameter=0x00)
response = f.serial.read(12)
print "Resp len:", len(response)
print "Response:", [hex(x) for x in bytearray(response)]
```

Also, current comments are not a Py3 compatibility issue, so I am going to close it. I am positive the issue is either in checksum, or in the connectivity. Both of the things you have to debug on your side, and I cannot do it remotely. Note that this project is just an example for an interface, and not a universal solution, so it is supposed to work assuming you have everything setup.

If you want to fix the codes, you can submit a PR, I will merge them after a review.

**Comment by fxrhxn** [comment] 2017-01-23 23:13
Ok, thank you for your help. I really appreciate it. Can I ask you what checksum is?

**Comment by fxrhxn** [comment] 2017-01-23 23:16
Btw here is the response for the new code : 

```

Send status: True
Resp len: 7
Response: ['0x0', '0x0', '0x0', '0x0', '0x0', '0x30', '0x1
```

']

**Comment by zafartahirov** [comment] 2017-01-23 23:30
Serial protocol uses checksum to make sure that the packets sent/received were not corrupted. Sometimes, the checksum is automatically checked, but most of the time it is reported to the user for checking ([info](https://en.wikipedia.org/wiki/Universal_asynchronous_receiver/transmitter)).

From the response you posted, it looks like you are not receiving the whole message back. This could happen due to multiple reasons -- your wires are too long and communication speed too fast, or your timeout is too short.  Also, I have noticed that you have response length to be different now, from what it was before - do you have a huge resistor at the link (don't use anything bigger than 1k)? If resistor is too big, it might cause a slow rise/fall time, and sometimes even fail (due to internal pullup/pulldown).

With that said, if you want to use a serial communication, you first need to make sure you are able to send/receive the data across a link without the use of any 3rd party code. Try sending the requests using a terminal -- you can use `echo -ne '<command message here>' > /dev/ttyS0` and read it using `cat -v < /dev/ttyS0` ([more info](http://unix.stackexchange.com/questions/117037/how-to-send-data-to-a-serial-port-and-see-any-answer)). Ideally, you want to be able to interface the RPi to the scanner from the terminal. That way you can pinpoint where the problem is originating from.

Once you are able to use terminal to talk to the scanner, `fingerpi` will just make your life a little easier by abstracting most of the commands and response decoding.

**Closed by zafartahirov** 2017-01-23 23:30 UTC
